language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - 101.132.193.88
before_install:
- pwd
- openssl aes-256-cbc -K $encrypted_ee699fc33e43_key -iv $encrypted_ee699fc33e43_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@101.132.193.88 -o StrictHostKeyChecking=no 'cd /www/pc && git pull && npm
  install && npm run build'
